# Generated by Django 4.1.4 on 2022-12-08 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('api_key', models.CharField(max_length=255, unique=True)),
                ('check_type', models.CharField(choices=[('Kitchen', 'Kitchen'), ('Client', 'Client')], max_length=20)),
                ('point_id', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Kitchen', 'Kitchen'), ('Client', 'Client')], max_length=20)),
                ('order', models.JSONField()),
                ('status', models.CharField(choices=[('New', 'New'), ('Rendered', 'Rendered'), ('Printed', 'Printed')], max_length=20)),
                ('pdf_file', models.FileField(upload_to='')),
                ('printer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.printer')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
