# Generated by Django 4.1.4 on 2022-12-12 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_check_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printer',
            options={'ordering': ['id']},
        ),
    ]
